# Generated by Django 5.2 on 2025-04-20 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='cpf',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
